export HASS_TOKEN="{{ op://Private/Home Assistant/access_token }}"
export OPENAI_API_KEY="{{ op://Private/OpenAI API Key/Anmeldedaten }}"
export ANTHROPIC_API_KEY="{{ op://Private/Anthropic Claude API/Anmeldedaten }}"
export OPENROUTER_API_KEY="{{ op://Private/Openrouter API/Anmeldedaten }}"
export DEEPSEEK_API_KEY="{{ op://Private/cvtvyubg6wtxjhe3pjwb7z5w6e/Anmeldedaten }}"
export GEMINI_API_KEY="{{ op://Private/Gemini API Key/Anmeldedaten }}"
export GOOGLE_AI_API_KEY="$GEMINI_API_KEY"
