tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "buo/cask-upgrade"

# Formulas
brew "xz"
brew "bat"
brew "curl"
brew "dvc"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnu-sed"
brew "htop"
brew "hub"
brew "jq"
brew "jid"
brew "mariadb-connector-c"
brew "ncdu"
brew "nmap"
brew "node"
brew "pipenv"
brew "prettyping"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "svn"
brew "tree"
brew "wget"
brew "xsv"
brew "yazi"
brew "ffmpegthumbnailer"
brew "unar"
brew "z"
brew "zsh"
brew "zellij"
brew "zoxide"
brew "mas"

# Casks
cask "temurin"
cask "angry-ip-scanner"
cask "appzapper"
cask "balenaetcher"
cask "dash"
cask "discord"
cask "docker"
cask "fantastical"
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "google-drive"
cask "gpg-suite"
cask "istat-menus"
cask "iterm2"
cask "keyboard-cleaner"
cask "latexit"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-office"
cask "ngrok"
cask "notion"
cask "nvidia-geforce-now"
cask "parsec"
cask "philips-hue-sync"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "rectangle"
cask "rescuetime"
cask "rowanj-gitx"
cask "r"
cask "rstudio"
cask "raycast"
cask "signal"
cask "skype"
cask "slack"
cask "spotify"
cask "steelseries-gg"
cask "suspicious-package"
cask "tableplus"
cask "telegram"
cask "the-unarchiver"
cask "tunnelblick"
cask "vagrant"
#cask "virtualbox"
#cask "virtualbox-extension-pack"
cask "viscosity"
cask "visual-studio-code"
cask "webpquicklook"
cask "whatsapp"
cask "zoom"

# Mac App Store
mas "Amphetamine", id: 937984704
mas "Cardhop", id: 1290358394
mas "Keynote", id: 409183694
mas "MoneyMoney", id: 872698314
mas "Monosnap", id: 540348655
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Passepartout", id: 1433648537
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Save to Pocket", id: 1477385213
mas "Todoist", id: 585829637
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
