tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/services"
brew "xz"
brew "bat"
brew "curl"
brew "direnv"
brew "dvc"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "fzf"
brew "gh"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnu-sed"
brew "htop"
brew "hub"
brew "jenv"
brew "jid"
brew "jq"
brew "mariadb-connector-c"
brew "mas"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node"
brew "ollama", restart_service: true
brew "pipenv"
brew "prettyping"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "starship"
brew "tree"
brew "unar"
brew "wget"
brew "xsv"
brew "yazi"
brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "1password-cli"
cask "arc"
cask "balenaetcher"
cask "dash"
cask "discord"
cask "docker"
cask "fantastical"
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "google-drive"
cask "gpg-suite"
cask "istat-menus"
cask "iterm2"
cask "keyboard-cleaner"
cask "kitty"
cask "latexit"
cask "linearmouse"
cask "moonlight"
cask "ngrok"
cask "notion"
cask "nvidia-geforce-now"
cask "parsec"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "r"
cask "raycast"
cask "rectangle"
cask "rescuetime"
cask "rstudio"
cask "signal"
cask "skype"
cask "slack"
cask "spotify"
cask "suspicious-package"
cask "telegram"
cask "temurin"
cask "the-unarchiver"
cask "viscosity"
cask "visual-studio-code"
cask "webpquicklook"
cask "whatsapp"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Cardhop", id: 1290358394
mas "Keynote", id: 409183694
mas "MoneyMoney", id: 872698314
mas "Monosnap", id: 540348655
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Passepartout", id: 1433648537
mas "Pocket", id: 568494494
mas "PopClip", id: 445189367
mas "Save to Pocket", id: 1477385213
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "eamodio.gitlens"
vscode "fwcd.kotlin"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "iterative.dvc"
vscode "iterative.vscode-dvc-pack"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-de"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "rjmacarthy.twinny"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "vstirbu.vscode-mermaid-preview"
vscode "zainchen.json"
