export HASS_TOKEN="{{ op://Private/Home Assistant/access_token }}"
export OPENAI_API_KEY="{{ op://Private/OpenAI API Key/Anmeldedaten }}"
export ANTHROPIC_API_KEY="{{ op://Private/Claude/Anmeldedaten }}"
export OPENROUTER_API_KEY="{{ op://Private/Openrouter/Anmeldedaten }}"
export DEEPSEEK_API_KEY="{{ op://Private/cvtvyubg6wtxjhe3pjwb7z5w6e/Anmeldedaten }}"